-- MySQL Script generated by MySQL Workbench
-- Wed Feb 26 11:40:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SchoolManager
-- -----------------------------------------------------
-- This is the database presentation of School Manager application version 1.
DROP SCHEMA IF EXISTS `SchoolManager` ;

-- -----------------------------------------------------
-- Schema SchoolManager
--
-- This is the database presentation of School Manager application version 1.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SchoolManager` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `SchoolManager` ;

-- -----------------------------------------------------
-- Table `SchoolManager`.`Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolManager`.`Classroom` ;

CREATE TABLE IF NOT EXISTS `SchoolManager`.`Classroom` (
  `id` LONGTEXT NOT NULL COMMENT 'It is classroom\'s unique identifer.',
  `name` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is classroom\'s name.',
  `capacity` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is the number of maximum students what the classroom can contain.\nThe minimum value is 10 students.',
  `level` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is the identifier of classroom\'s level.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Classroom_Level1_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `fk_Classroom_Level1`
    FOREIGN KEY (`level`)
    REFERENCES `SchoolManager`.`Level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'It is the table which contains the classroom informations.';


-- -----------------------------------------------------
-- Table `SchoolManager`.`Level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolManager`.`Level` ;

CREATE TABLE IF NOT EXISTS `SchoolManager`.`Level` (
  `id` LONGTEXT NOT NULL COMMENT 'It is ',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is level\'s name.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'It is the table which contains the level informations.';


-- -----------------------------------------------------
-- Table `SchoolManager`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolManager`.`Student` ;

CREATE TABLE IF NOT EXISTS `SchoolManager`.`Student` (
  `id` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is student unique identifier.',
  `firstName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is student\'s first name.',
  `lastName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is student\'s last name.',
  `birthday` DATE NOT NULL COMMENT 'It is student\'s birthday date.',
  `level` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is the identifier of student\'\'s level.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Student_Level1_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Level1`
    FOREIGN KEY (`level`)
    REFERENCES `SchoolManager`.`Level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'It is the table which contains the student informations.';


-- -----------------------------------------------------
-- Table `SchoolManager`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolManager`.`Subject` ;

CREATE TABLE IF NOT EXISTS `SchoolManager`.`Subject` (
  `id` LONGTEXT NOT NULL COMMENT 'it is subject unique identifier.',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is subject\'s name.',
  `level` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is the identifier of subject\'s level.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Subject_Level_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Level`
    FOREIGN KEY (`level`)
    REFERENCES `SchoolManager`.`Level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'It is the table which contains the subject informations.';


-- -----------------------------------------------------
-- Table `SchoolManager`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SchoolManager`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `SchoolManager`.`Teacher` (
  `id` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is teacher\'s unique identifier.',
  `firstName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is teacher\'s first name.',
  `lastName` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is teacher\'s last name.',
  `birthday` DATE NOT NULL COMMENT 'It is teacher\'s birthday date.',
  `level` LONGTEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT 'It is the identifier of teacher\'s teaching level.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Teacher_Level1_idx` (`level` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Level1`
    FOREIGN KEY (`level`)
    REFERENCES `SchoolManager`.`Level` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'It is the table which contains the teacher informations.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
